export const ENV = {
  SERVER_HOST: "",
  API_URL: "http://localhost:4000",
  API_LV: "http://localhost:8000",
  ENDPOINTS: {
    AUTH: {
      REGISTER: "auth/register",
      LOGIN: "auth/login",
    },
    USER: {
      GETUSER: "auth/user",
    },
    LABS: {
      LABS: "labs/",
      LABORATORIOS: "labs/laboratorioscnts",
      LABORATORIOSDB: "labs/laboratoriosdb",
      LABSMONITORING: "labs/labsmonitoring",
      WRITEFILES: "labs/writeTofiles",
      DATES: "labs/dates",
      ACTIVIDADES: "labs/actividades",
      LASTACTIVIDAD: "labs/lastactividad",
      PCS: "labs/pcs",
      VALIDATE: "labs/existFile",
      PROG: "labs/prog",
      UPTDATELAB: "labs/updateLaboratorio",
      PROGRAMACIONES: "labs/programaciones",
      DELETEPROGRAMACION: "labs/deleteProgramacion",
      UPDATEPROGRAMACION: "labs/updateProgramacion",
      CREATEPROGRAMACION: "labs/createProgramacion",
      CREATEA: "labs/createA",
      CREATEW: "labs/createW",
      CREATEDURACION: "labs/createDuracion",
      CREATEAPP: "labs/createAplicacion",
      DELETEDAPP: "labs/deleteAplicacion",
      APLICACIONES: "labs/aplicaciones",
    },
  },
  TOKEN: "token",
  AUTNGINX: {
    USERNAME: "admin",
    PASSWORD: "Ty22-Op4a",
  },
};
